name: inquiry
version: 0.1.0.0
github: "myme/inquiry"
license: BSD3
author: "Martin Myrseth"
maintainer: "mm@myme.no"
copyright: "2018-2022 Martin Myrseth"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/myme/inquiry#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src
  dependencies:
    - brick
    - microlens-platform
    - process
    - text
    - text-zipper
    - vty

executables:
  inquiry:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - inquiry

tests:
  inquiry-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - inquiry
      - microlens-platform
      - QuickCheck
